### ISSUE TITLE
on form submit call an arbitrary command line

### ISSUE THREAD

**Issue by costezki** [costezki/fingerprinter-ui#3]
on form submit for diff or stats forms, call a server method that generates an arbitrary file (e.g. uui4) and adds it to a file collection.
the file collection then makes it available for download.

**Comment by costezki** [comment]
1. form -> configuration files
* write/upload CVS files to server/collection
* generate JSON
2. configuration file -> PDF report
* call Python code/bash script with parameters
* expect report or errors
3. if available add report to collection 
4. download report OR show errors
* if report is available in collection offer download link
* if error -> show error

**Comment by LordGarod** [comment]
Done
